### ISSUE TITLE
multiprocessing.pool.MaybeEncodingError

### ISSUE THREAD

**Issue by CrusheerPL** [RusheerPL/demGenerator#1]
```
Traceback (most recent call last):
  File "C:\Users\...\Desktop\demGenerator-master\demGenerator-master\demGenerator_mod2.py", line 113, in <module>
    hstr = list(tqdm.tqdm(p.imap(getHeightPL, rqs), total=len(rqs)))
  File "C:\Python\Python37\lib\site-packages\tqdm\std.py", line 1081, in __iter__
    for obj in iterable:
  File "C:\Python\Python37\lib\multiprocessing\pool.py", line 748, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x000001EF13C26400>'. Reason: 'TypeError("cannot serialize '_io.BufferedReader' object")'
```

**Comment by CrusheerPL** [comment]
Problem solved: https://github.com/RusheerPL/demGenerator/commit/f5e3f5f64bcde989ce82f3cb078376e700174938
